### ISSUE TITLE
Is there a way to run this without alerting Defender?

### ISSUE THREAD

**Issue by JeffreyShran** [Leo4j/Amnesiac#3]
Thanks for releasing this tool. I tried it today and got busted by defender as soon as I ran the first "load and run" command.

Are you using some stealth technique to run the tool?

I'm in a corporate environment BTW.

**Comment by Leo4j** [comment]
Hi Jeffrey. I believe bypassing Defender is off topic here, as it is not an issue specific to this tool. There are many resources online that will help you with that.
What I can say is that I’ve managed to run the tool successfully against Defender and Sophos lately, therefore it may be that it comes down to Defender corporate-specific configuration.
There may be web filtering coming into play (Github), or in-memory loading in general.
Have you tried saving the Amnesiac raw code to disk and loading it from there ? Create an Amnesiac.ps1 file on disk, copy/paste/save the raw script content from Github into Amnesiac.ps1, then run the tool `. .\Amnesiac.ps1`.
If detection is not specific to Amnesiac, this method may let you run it.
Hope this helps, let me know

**Comment by JeffreyShran** [comment]
Thanks for replying @Leo4j :)

I forgot to add that I did try the .ps1/raw approach and our SoC caught that too. I guess it is just that we have a tight configuration as you point out. Which is great in reality for the business!
